### PR TITLE
Added support for token auth

### PR DESCRIPTION
**Pull request by sunng87**
## Description

This patch adds support for [token auth](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#token-authentication) to make it easier to use backward compatibility API of influxdb 2.0

### Checklist
- [x] Formatted code using `cargo fmt --all`
- [x] Linted code using clippy `cargo clippy --all-targets --all-features -- -D warnings`
- [x] Updated README.md using `cargo readme -r influxdb -t ../README.tpl > README.md`
- [x] Reviewed the diff. Did you leave any print statements or unnecessary comments?
- [x] Any unfinished work that warrants a separate issue captured in an issue with a TODO code comment

### TODO items
- [x] improve github workflow and integration tests to test on influxdb 1.8 and 2.0 individually
- [ ] add doc for influxdb 2.0 authorization usage. For now, the `username`/`password` auth is not compatible with 1.x so you can only use token auth on 2.0.

### CODE REVIEW

**Comment by sunng87** [comment]
TODO: improve integration tests to test on influxdb v1 and v2 individually.

**Comment by Empty2k12** [comment]
@sunng87 Thanks for this contribution! 🚀 What's your plan to get this merged? Is there anything I can help you with?

**Review by moisesdelacruz — APPROVED** [review]

**Comment by moisesdelacruz** [comment]
I just did tests with InfluxQL in cURL in terminal and it works very fast (milliseconds), now the same query takes up to 19 seconds in influxdb-rust.

**Comment by Empty2k12** [comment]
@moisesdelacruz Could you open a separate issue with the curl command you're using and the code snippet which is taking so long? Thanks!

**Comment by moisesdelacruz** [comment]
@Empty2k12 Thanks for answering, comment here, because the test was done with Influxdb v2 and the branch of this PR.

But I will open the new Issue.

**Comment by Empty2k12** [comment]
@moisesdelacruz Sorry for misunderstanding, thought you were having an issue with the released library. If it's caused by this PR, here's the right place.

**Comment by moisesdelacruz** [comment]
In this case it is bringing a month of data, where in every second there is at least one record.

-   Rust Version: rustc 1.50.0 (cb75ad5db 2021-02-10)
-   Runtime version (e.g. Tokio): 0.2.22
-   OS Version: MacOS 10.14.6

Steps to Reproduce:
```rs
#[tokio::main]
async fn main() {
    // Connect to db `test` on `http://localhost:8086`
    let client = Client::new("https://influxdb-host", "example_db")
        .with_token("jwt");

    // Let's see if the data we wrote is there
    let read_query = Query::raw_read_query("SELECT * FROM example_db.example_rp.history WHERE tag='example'");

    let start = Time::now();
    let result = client
        .query(&read_query)
        .await;
    let end = Time::now();

    println!("{}", result.unwrap());
    println!("{:?}", end - start); // Duration { seconds: 16, nanoseconds: 823561000 }
}
```

VS

```sh
curl --get https://influxdb-host/query?db=example_db \
  --header "Authorization: Token jwt" \
  --data-urlencode "q=SELECT * FROM example_db.example_rp.history WHERE tag='example'"

# took miliseconds
```

**Comment by sunng87** [comment]
@Empty2k12 Sorry for late response. I have been pretty busy these days. Most work should have been done. I'm going to setup CI to verify the lib on both InfluxDB 1.x and 2.0

**Comment by moisesdelacruz** [comment]
Hello @Empty2k12 and @sunng87, I have already checked this PR on several occasions, and I think that the performance problem comes from before and not from this feature, unfortunately, all my data is in Influxdb v2 and I cannot test with the published version of this module.

This PR looks good, I think we should look for the problem in another issue.

Issue: https://github.com/Empty2k12/influxdb-rust/issues/91

**Comment by isarrider** [comment]
is there an update here?

**Comment by fredrik-jansson-se** [comment]
Any update? I was hoping to use the rust client in a project, seems like I'm blocked atm.

**Comment by msrd0** [comment]
@fredrik-jansson-se If there were any updates, they would be posted here.

Someone needs to rebase these changes onto the main branch and setup CI to test with influxdb v2.0.

**Comment by msrd0** [comment]
This change has been merged as part of #118

**Pull request closed without merging**
